package rehabilitationzoo.db.pojos;

public enum IllnessName {
	
	//OINTMENT, ANALGESIC, ANTIBIOTIC, ANTI_INFLAMATORY, BANDAGE, ANTIBODIES_SERUM
	RASH, FEVER, STYES, PARASITES, SCABIES, POX, CHLAMYDIA, FIV, RABIES, BLUETONGUE, SALMONELLA, DIHARREA, FOOTROT

}
